language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - osx
    - linux

cache:
    apt: true
    directories:
        - $HOME/.pyenv
        - $HOME/.venv
        - $HOME/.cache/pip

env:
    matrix:
        - TOXENV=coverage
        - TOXENV=lint
        - TOXENV=examples2
        - TOXENV=examples3
        - TOXENV=pypy
        - TOXENV=py34
        - TOXENV=py27
        - TOXENV=pypy3
        - TOXENV=py33

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

matrix:
    exclude:
        - os: linux
          env: TOXENV=examples2
        - os: osx
          env: TOXENV=examples3
        - os: osx
          env: TOXENV=coverage
        - os: osx
          env: TOXENV=lint
        - os: osx
          env: TOXENV=pypy
        - os: linux
          env: TOXENV=pypy3
        - os: linux
          env: TOXENV=py27
        - os: linux
          env: TOXENV=py33
        - os: osx
          env: TOXENV=py34
